/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bags: typeof import('./src/components/Bags.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Goods: typeof import('./src/components/Goods.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartScreen: typeof import('./src/components/StartScreen.vue')['default']
    Wallets: typeof import('./src/components/Wallets.vue')['default']
  }
}
